### ISSUE TITLE
show file name

### ISSUE THREAD

**Issue by dcordovez** [novafacile/novagallery#14]
Hello!
I am very interested in acquiring the licensed version. Is it possible to configure so that the file name is displayed along with the photo?

**Comment by dcordovez** [comment]
Thank you!
I have already bought the license. Should I receive an email with the download or do I use the same files as the free version?

**Comment by david-novafacile** [comment]
You should have received an email from Paddle with the download link and support info right after your order.

If you haven't received it, I can also send you the download link from novaGallery Pro Support. Just send a short email to support@novagallery.org

**Comment by david-novafacile** [comment]
seems to be solved.
