### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by patience4711** [novafacile/novagallery#19]
I noticed that it's useless to lower the "imageSizeThumb" below  "200x200". I hoped to get more thumbs but they are only stretched to fit 4 in a row. So 4 thumbs seems the max in a page row.

As for a mobile page the max seems to be 1. This makes the concept of thumbs pointless because the thumb is streched to page width (and blurred) and when clicked we get an even smaller photo.
Is there a way to tweak this?

**Comment by david-novafacile** [comment]
If you want to use smaller thumbnails and show mir in a row, you have to build your own theme. You can copy one of the both and change the grid in `/yourthemename/album.php` how you like.

For example in basic theme: https://github.com/novafacile/novagallery/blob/main/src/nova-themes/novagallery/album.php

The layout is based on Bootstrap CSS Version 4: https://getbootstrap.com/docs/4.6/getting-started/introduction/

Don't forget to change theme name in `nova-config/site.php`

The image streching is set here:
https://github.com/novafacile/novagallery/blob/15b6e93c90e44994bd3da05f979d087ad38ce82b/src/nova-themes/novagallery/assets/style.css#L28-L36

**Comment by patience4711** [comment]
Thanks David but that is all to cryptic for me. Before i figure out at which chord to pull I wrote some even simpler php that does the job the way i want it. Based on the latest bootstrap.min.cs
Good luck and again thanks for sharing your good work.
