### ISSUE TITLE
Not closing PHP ?> is considered better practice

### ISSUE THREAD

**Issue by ibes** [novafacile/novagallery#2]
Hi there,

cool tool.
Seems to be just as much as needed to have a gallery. I like that style and love that I am able to get every line of the code as it is few enough lines to understand everything.

A small hint:
Not closing the PHP tags is considered better practice as it avoids the risk of having whitespace after them.

**Comment by david-novafacile** [comment]
Thank you very much! That is a good point and will be considered in the next version.

**Comment by david-novafacile** [comment]
Will be fixed in v2
