### ISSUE TITLE
404. always

### ISSUE THREAD

**Issue by slavamas** [novafacile/novagallery#23]
I seems followed all your explanations, but it keeps giving me 404. always.

**Comment by david-novafacile** [comment]
- Do you use a webspace provider or a self  installed server?
- Apache or nginx?
- installed on root Domain or in subfolder (e.g. yourdomain.tld/gallery)

**Comment by slavamas** [comment]
so far I am trying it out on my local virtual machine, so I have full, root
access to it.
when (and if) I get it working - it will be running on public server, which
I have full access to - self installed ubuntu 20.4
Apache
subfolder

**Comment by david-novafacile** [comment]
Most times it's one or both problemes:

- htaccess support is not enabled
- mod_rewrite is not enabled.

Please check in Apache config.

https://github.com/novafacile/novagallery/issues/4#issuecomment-1024972579

**Comment by slavamas** [comment]
OK.
1. no, I am not using .htaccess
2. for either problem - why then does it say : 404? because it cannot find
.htaccess file?

**Comment by slavamas** [comment]
and, I am sorry, perhaps, I missed/misunderstood something, but I don't
think your instructions say a word about htaccess or mod_rewrite

**Comment by david-novafacile** [comment]
Enabled htaccess support and mod_rewrite are mentioned in the requirements. This is part of the basic server setup of Apache with PHP and is required by any PHP program that uses speaking URLs.

The .htaccess file is in the root directory of novagallery, where the index.php is.

https://github.com/novafacile/novagallery/tree/main/src

**Comment by david-novafacile** [comment]
Do you see only 404 (Even on the first request) or do you see the first page and if you click on an album you see the 404?

**Comment by Monarch73** [comment]
@david-novafacile 404 is displayed when you explicitly request index.php from your server

@slavamas just don't request index.php directly....
