### ISSUE TITLE
"back" button not working properly

### ISSUE THREAD

**Issue by Benman2785** [novafacile/novagallery#29]
Hi,

i use Version 1.1.1

if i have an album with several folders i get and click i get "https://album/family" instead of "https://pics.domain.tld/album/family"

in my site.php i have to use "url": "/", - otherwise i get error

**Comment by Benman2785** [comment]
fixed it:
line 9 in album.php of theme
`<a href="<?php echo Site::url().'/'.Page::data('parentPage'); ?>" class="text-muted link-back">&laquo; <?php L::p('Back'); ?></a>`
changed to
`<a href="<?php echo Site::url().'../'.Page::data('parentPage'); ?>" class="text-muted link-back">&laquo; <?php L::p('Back'); ?></a>`

so all that was missing for nginx where two dots

**Comment by david-novafacile** [comment]
That's strange. Wich PHP version do you use?
