### ISSUE TITLE
Template "home" seems to be never loaded

### ISSUE THREAD

**Issue by ibes** [novafacile/novagallery#3]
https://github.com/novafacile/novagallery/blob/main/src/nova-base/app/pages/home.php#L22

Home Page calls "album" instead of "home" so home templates seems to be never used

**Comment by david-novafacile** [comment]
Thanks for the comment. In one of the last updates, the template use was simplified a little. It was forgotten to delete the no longer needed template.

**Comment by david-novafacile** [comment]
Is now fixed with v1.1.1.  Home template is now used again.
