### ISSUE TITLE
Adding Italian Messages...

### ISSUE THREAD

**Issue by LeonardoV123** [novafacile/novagallery#33]
To avoid merge problems... I created as issue...

if you want to add Italian messages, here is the file it.php

<?php defined("NOVA") or die(); ?>
{
  "login": "Iniziare sessione",
  "logout": "Terminare sessione",
  "password": "Password",
  "back": "Ritorno",
  "404-/-page-not-found": "404 / Pagina non trovata",
  "sorry-this-page-does-not-seem-to-exist": "Ci dispiace, questa pagina non sembra essere disponibile.",
  "back-to-home": "Tornare alla pagina principale"
}

Very good work !

while.... Merry Christmas !!

**Comment by Benman2785** [comment]
german would be:

{
"login": "einloggen",
"logout": "ausloggen",
"password": "Passwort",
"back": "zurück",
"404-/-page-not-found": "404 / Seite nicht gefunden",
"sorry-this-page-does-not-seem-to-exist": "Entschuldigung, diese Seite scheint nicht zu existieren.",
"back-to-home": "zurück zum Hauptmenü"
}

**Comment by david-novafacile** [comment]
Thank you very much. Added with https://github.com/novafacile/novagallery/commit/167c8233dc3cfc4be9651aa2fef9160f7d2b466bn
