### ISSUE TITLE
Number of albums limit?

### ISSUE THREAD

**Issue by FairbanksMike** [novafacile/novagallery#35]
I was wondering if there is a limit on the number of albums/sub-albums you can have?

I recently setup novaGallery and got it working well.  I initially uploaded 3 albums, 1 of which had 2 sub-albums, and all looked well.  I then proceeded to upload a Gallery structure with 11 main albums, but 327 total albums with 29682 image files.  But I only get the 3 original albums.  I tried deleting all the caches, that didn't help.  I then moved all the albums out of the galleries folder and cleaned up all the cache files.  While they were gone novaGallery showed an empty page.  I moved 1 album back in and it showed the 1 just fine... I then copied all of them back and once again it only shows 3.

I have another site I setup that only has 3 main albums, but has between 18 and 25 sub-albums in each of those main albums and it is working just fine.

So I'm wondering if I am limited to 3 main albums?

**Comment by Benman2785** [comment]
...
1. copy every thing into galleries folder that needs to be there
2. open the smallest album (least files in album) - WAIT!
3. when all photos are showing - choose next small album - WAIT!

there is a lot CPU for caching large albums - this takes time
note: if your webserver (apache or nginx) drop the request after X min/sec then you have to reload the page until the caching is finished.

i dont think that there is a limit in number of files or folders
so main limitation is lack of database and time it needs to cache large folders

**Comment by david-novafacile** [comment]
Right, there is no limit for albums or images. Like Benman2785 said, if you have a lot images and album, generating the images requires cpu and ram. Unfortunately there is no general recommendation for CPU & RAM requirements, as it depends on how large the images are and the general server environment. Once the image cache is built, there is no longer the problem.

With v2 it gets much better, as only the images are generated when they are really displayed. v2 is in internal alpha testing and gets public in next few months.
