### ISSUE TITLE
404 / Page Not Found

### ISSUE THREAD

**Issue by AsifTraders** [novafacile/novagallery#38]
I recently bought a Pro Version of Nova Gallery but when I put them into test using XAMPP running on my windows machine, it always encounters the same error no matter how hard I try to resolve this issue. Kindly, help me out with this.

![image](https://user-images.githubusercontent.com/127926768/225227420-36362c12-18ec-42f4-aa13-0355a365280b.png)

**Comment by david-novafacile** [comment]
Hi,

did you fixed it?

**Comment by AsifTraders** [comment]
Yeah, I fixed it. Thanks for asking though.
