### ISSUE TITLE
Shuffle Sort

### ISSUE THREAD

**Issue by rimexi** [novafacile/novagallery#39]
Is it Possible to Shuffle Gallery? Which File should be modified zu shuffle Fotos in a Page?

**Comment by david-novafacile** [comment]
This is already prepared for next release. 

You can replace this file with the file in the released package and use `random` in the config.

https://github.com/novafacile/novagallery/blob/main/src/nova-base/lib/novaGallery.php

**Comment by rimexi** [comment]
Thanks. It works 🥇
