### ISSUE TITLE
Adding the file name in the theme

### ISSUE THREAD

**Issue by pierrebehel** [novafacile/novagallery#42]
Hello.
This gallery is really simple and efficient. 
But I've a problem : I need to have the name of the files under the thumbnails in the album page (http://novagallery.pierrebehel.com/album/2023-09-02_amboise) under each picture and also in the full page picture (http://novagallery.pierrebehel.com/album/2023-09-02_amboise#pid=9).
How am I abble to do that ?
I've bought a Pro Version. 
I'm not a developer but I can open a PHP file and modify it after having duplicate the theme folder with a new name. I've modified the configuration without problem. 
Thank you.

**Comment by david-novafacile** [comment]
Hi Pierre,

here is a small description: https://github.com/novafacile/novagallery/issues/14#issuecomment-1196813078 

Does it help?
