### ISSUE TITLE
enhancement: choose your own subdirectory?

### ISSUE THREAD

**Issue by dchmelik** [novafacile/novagallery#5]
I finally got my art novaGallery](http://davidchmelik.com/gallery/) working, but couldn't choose my directory.  It's not always secure to show what one uses, but for now I'm at least leaving novaGallery tag at the top.  However I'd like to 'RewriteBase /galllery' but that led to a 404...

**Comment by david-novafacile** [comment]
Sorry, I don't understand that correctly.

You can also use novaGallery under your own folder name, e.g. yourdomain.com/gallery.

Then you just have to change this in the configuration (URL in `nova-config/site.php` and RewriteBase in `.htaccess`)

**Comment by dchmelik** [comment]
Oaky; it hadn't worked for some other reason but after your recent email, it works now; wasn't a problem.
